### ISSUE TITLE
Specifying superuser.password doesn't set admin password

### ISSUE THREAD

**Issue by alop** [bootc/netbox-chart#33]
Passing `--set superuser.password=FooBar` doesn't actually set this admin password.
Still need to login with default admin/admin

Even setting `skipStartupScripts=false` doesn't seem to have an effect on this.

**Comment by bootc** [comment]
The `admin` user is only created (with the given password) if it doesn't exist already. If you've installed the chart and NetBox has started once with the default settings, the previously created superuser will not be changed. The only way around this is to choose a different, non-existent, user in the chart configuration which will trigger a new user to be created.

This is currently the expected behaviour in the upstream container images: https://github.com/netbox-community/netbox-docker/blob/c80fb19507679938528817ab8a9b03514bd1e8be/docker/docker-entrypoint.sh#L28-L58.
